version: '3'
services:
  app:
    build: './frontend/'
    ports:
    - "8080:80"
    depends_on:
      - backend
      - db
  backend:
    build: './backend/'
    ports:
    - "8081:8080"
    depends_on:
      - db
  db:
    build: './db/'  
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ht
    ports:
      - "3306:3306"
