version: '3'
services:
  db:
    build: './db'
    volumes:
      - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql    
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ht
    ports:
      - "3306:3306"
