version: '3'
services:
  app:
    build: './frontend/'
    ports:
     - "8080:80"
    depends_on:
      - backend
      - db
  backend:
    build: './backend/'
    ports:
      - "8081:8080"
    depends_on:
      - db
  db:
    image: mariadb:10.3
    volumes:
      - container-volume:/var/lib/mysql
      - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql    
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ht
    ports:
      - "3306:3306"
volumes:
  container-volume:
