version: '3'
services:
  app:
    build: './frontend/'
    ports:
     - "8080:80"
  backend:
    build: './backend/'
  db:
    image: mariadb:10.3
    volumes:
      - container-volume:/var/lib/mysql
      - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql    